# Numpy Revision

In [1]:
import numpy as np

In [2]:
#Numpy ==> Numerical python (used for scientific calculation )
#          (open source library)

# How to create an user define array from list ?

In [3]:
a=[1,3,5,66,77]
type(a)

list

In [4]:
b= np.array(a)
b

array([ 1,  3,  5, 66, 77])

In [5]:
a=[]
size = int(input("enter size:"))
for i in range (size):
    val = int(input(" enter the value:"))
    a.append(val)
    
b=np.array(a)
b

enter size:4
 enter the value:22
 enter the value:33
 enter the value:44
 enter the value:55


array([22, 33, 44, 55])

In [7]:
a=[11,33,5],[33,4,5],[44,5,6]
a

([11, 33, 5], [33, 4, 5], [44, 5, 6])

# How to check size and shape and total elements of an array?

In [16]:
print("total dimensions of this array:", b.ndim)
print("shape of this array:", b.shape)
print("total elemnts of this array:", b.shape)

total dimensions of this array: 1
shape of this array: (4,)
total elemnts of this array: (4,)


In [17]:
# n(total_elements ) = n(rows)*n(columns)

# Pre - defined FUNCTIONS

# 1. zeros()== > it will create an array  in which all values are zeros

In [20]:
a=np.zeros(2)
a

array([0., 0.])

In [23]:
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
print("total dimensions of this array:", a.ndim)
print("shape of this array:", a.shape)
print("total elemnts of this array:", a.shape)

total dimensions of this array: 2
shape of this array: (3, 4)
total elemnts of this array: (3, 4)


# (2). ones()==> this will create an array in which all the values are 1

In [26]:
a=np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [27]:
a=np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
print("total dimensions of this array:", a.ndim)
print("shape of this array:", a.shape)
print("total elemnts of this array:", a.shape)

total dimensions of this array: 2
shape of this array: (3, 4)
total elemnts of this array: (3, 4)


In [29]:
#diagonal elements =[(1,1),(2,2),(3,3),(4,4)..........(n,n)]
#symmentric matrix = n(rows) = n(columns)
#asymmentric matrix = n (rows)! = n (columns)

# 3. eye() ==> this will create an array in which diagonal position elemnts 1 and rest all are 0

In [30]:
a=np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [31]:
a= np.eye(4,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# (4) diag() ==> it will create an array in which we can pass our custom array value in the diagonal position and rest all are zeros

In [32]:
a=np.diag([2,3,445,33])
a

array([[  2,   0,   0,   0],
       [  0,   3,   0,   0],
       [  0,   0, 445,   0],
       [  0,   0,   0,  33]])